---
name: $(BuildDefinitionName)_$(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
    - main
    exclude:
      - develop
      - bug*
      - feature*

parameters:
  - name: AGENT_AMOUNT
    displayName: "The amount of agents you require"
    default: "1"
    type: string

  - name: CONTEXT
    displayName: "The the path to your dockerfile"
    default: "tooling-container/container"
    type: string

  - name: DOCKERFILE_NAME
    displayName: "The name of the Dockerfile"
    default: "Dockerfile"
    type: string

  - name: REGISTRY
    displayName: "The target registry"
    default: "ghcr.io"
    type: string

  - name: IMAGE_NAME
    displayName: "The name of the image"
    default: "tooling-container"
    type: string

  - name: TAGS
    displayName: "The tag of the image"
    type: string
    default: ":latest"

  - name: HOSTED_AGENT_IMAGE
    displayName: "The name of the vmImage"
    default: "ubuntu-latest"
    type: string

  - name: PYTHON3_VERSION
    displayName: "The version of python to be installed by from source"
    type: string
    default: "3.10.4"

  - name: GO_VERSION
    displayName: "The version of Go to be installed"
    type: string
    default: "1.18.`"

  - name: JAVA_VERSION
    displayName: "The version of java to be installed"
    type: string
    default: "17"

  - name: DOTNET_VERSION
    displayName: "The version of Dotnet to be installed"
    default: "6.0"
    type: string

  - name: SECRETS_VARIABLE_GROUP
    displayName: "The name of the variable group holding the secrets"
    default: "LBDO_DOCKER_SECRETS"
    type: string

  - name: USERNAME
    displayName: "Username to be passed for registry login, should reference a secret"
    default: $(USERNAME)
    type: string

  - name: PASSWORD
    displayName: "Password or access token for registry login, remember to store this in a keyvault or encrypted variable"
    default: $(PASSWORD)
    type: string
    
  - name: AZP_SECRETS_VARIABLE_GROUP
    displayName: "The name of the variable group holding the secrets"
    default: "LINUX_AZURE_DEVOPS_SECRETS"
    type: string

  - name: TEMPLATE_PATH
    displayName: "The name of the variable group holding the secrets"
    default: ".templates/template.yml"
    type: string
    
  - name: COUNT
    default: "1"
    displayName: "The amount that the count should start at"
    type: string

variables:
  - group: ${{ parameters.SECRETS_VARIABLE_GROUP }}
  - group: ${{ parameters.AZP_SECRETS_VARIABLE_GROUP }}

jobs:
  - template: ${{ parameters.TEMPLATE_PATH }}
    parameters:
      AGENT_AMOUNT: ${{ parameters.AGENT_AMOUNT }}
      USERNAME: ${{ parameters.USERNAME }}
      PASSWORD: ${{ parameters.PASSWORD }}
      CONTEXT: ${{ parameters.CONTEXT }}
      DOCKERFILE_NAME: ${{ parameters.DOCKERFILE_NAME }}
      REGISTRY: ${{ parameters.REGISTRY }}
      PYTHON3_VERSION: ${{ parameters.PYTHON3_VERSION }}
      DOTNET_VERSION: ${{ parameters.DOTNET_VERSION }}
      GO_VERSION: ${{ parameters.GO_VERSION }}
      JAVA_VERSION: ${{ parameters.JAVA_VERSION }}
      IMAGE_NAME: ${{ parameters.IMAGE_NAME }}
      TAGS: ${{ parameters.TAGS }}
